### ISSUE TITLE
Move utitlity functions to /utils

### ISSUE THREAD

**Issue by shaansubbaiah** [shaansubbaiah/Portfolio#32]
Currently `getData.js`, `getAvatar.js`, and `build.js` are in the repository root directory. Move them to a new folder `utils`. This should keep the repo more organized.

**Comment by Guzzler** [comment]
i could pick this up but would like to recommend maybe a better restructure of the files. would that be possible @shaansubbaiah ?

**Comment by shaansubbaiah** [comment]
Hey @Guzzler, I think @hafizmuhammadshoaib has attempted a fix but hasn't yet changed the paths in the files. We'll wait for him to fix that, if not you can take it up.

How do you recommend that we restructure the project better?

**Comment by Guzzler** [comment]
just doing a basic overview of the code you want restructured i would recommend changing the build file to actually use smaller helpers instead of a large chain of ifs for each if statement as well as have the getAvatar and getData both renamed and put in a singular util file as they use alot of similar imports. We can keep the build at the root since that is usually something required to be used regularly when changed. These are just a few changes from my first impressions. Do let me know what you think @shaansubbaiah
